# User and project
username: orchid
root_folder: www

# Modules control
nginx_install: true
mysql_install: true
phpmyadmin_install: true
php_install: true

# PHP versions
php_versions:
  - 8.1
  - 8.2
  - 8.3